### ISSUE TITLE
train.py without Deepspeed

### ISSUE THREAD

**Issue by petergreis** [hf-lin/ChatMusician#15]
Could I request that a train.py be created that does not use DeepSpeed?

**Comment by hf-lin** [comment]
Here is another work finetuned on LLaMA: [Goat: Fine-tuned LLaMA Outperforms GPT-4 on Arithmetic Tasks](https://github.com/liutiedong/goat)
It used transformers [Trainer](https://huggingface.co/docs/transformers/main_classes/trainer) pipeline to train models. Hope you find this repo helpful.

**Comment by petergreis** [comment]
Will submit my code in the near future, I have a single cpu/gpu python training script.
