### ISSUE TITLE
Open compass hangs...

### ISSUE THREAD

**Issue by petergreis** [hf-lin/ChatMusician#17]
Filed the bug directly with open compass: [open compass hangs when evaluating chat musician trained model - waiting for semaphore?](https://github.com/open-compass/opencompass/issues/1034)

**Comment by hf-lin** [comment]
@Magnetic2014 any ideas?

**Comment by petergreis** [comment]
Found a solution; there is a threading deadlock which is fixed with
`export MKL_THREADING_LAYER=GNU`
in the shell before running

[Issue at opencompass](https://github.com/open-compass/opencompass/issues/1034l)
